/* Generated by Pyrex 0.9.3.1 on Sun Jun 17 18:37:52 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "stdio.h"
#include "stdlib.h"
#include "xpa.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from xpa */

staticforward PyTypeObject __pyx_type_3xpa_xpa;

struct __pyx_obj_3xpa_xpa {
  PyObject_HEAD
  XPARec (*_xpa);
  char (*_template);
};

static PyTypeObject *__pyx_ptype_3xpa_xpa = 0;
static PyObject *__pyx_k2;
static PyObject *__pyx_k4;
static PyObject *__pyx_k6;
static PyObject *__pyx_k8;
static PyObject *__pyx_k10;
static PyObject *__pyx_k11;
static PyObject *__pyx_k13;
static PyObject *__pyx_k15;
static PyObject *__pyx_k16;
static PyObject *(__pyx_f_3xpa__get(XPARec (*),char (*),char (*))); /*proto*/
static PyObject *(__pyx_f_3xpa__set(XPARec (*),char (*),char (*),PyObject *)); /*proto*/

/* Implementation of xpa */

static char (__pyx_k1[]) = "*";
static char (__pyx_k3[]) = "*";
static char (__pyx_k5[]) = "";
static char (__pyx_k7[]) = "*";
static char (__pyx_k9[]) = "";
static char (__pyx_k12[]) = "";
static char (__pyx_k14[]) = "";

static PyObject *__pyx_n_nslookup;
static PyObject *__pyx_n_get;
static PyObject *__pyx_n_set;

static PyObject *__pyx_k1p;
static PyObject *__pyx_k3p;
static PyObject *__pyx_k5p;
static PyObject *__pyx_k7p;
static PyObject *__pyx_k9p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k14p;

static PyObject *__pyx_n_append;

static char (__pyx_k17[]) = "g";

static PyObject *__pyx_f_3xpa_nslookup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_nslookup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_template = 0;
  char (*(*__pyx_v_classes));
  char (*(*__pyx_v_names));
  char (*(*__pyx_v_methods));
  char (*(*__pyx_v_infos));
  int __pyx_v_i;
  int __pyx_v_n;
  int __pyx_v_iter;
  PyObject *__pyx_v_l;
  PyObject *__pyx_v_s;
  PyObject *__pyx_r;
  char (*__pyx_1);
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  static char *__pyx_argnames[] = {"template",0};
  __pyx_v_template = __pyx_k2;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_template)) return 0;
  Py_INCREF(__pyx_v_template);
  __pyx_v_l = Py_None; Py_INCREF(__pyx_v_l);
  __pyx_v_s = Py_None; Py_INCREF(__pyx_v_s);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":49 */
  __pyx_1 = PyString_AsString(__pyx_v_template); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  __pyx_v_n = XPANSLookup(0,__pyx_1,__pyx_k17,(&__pyx_v_classes),(&__pyx_v_names),(&__pyx_v_methods),(&__pyx_v_infos));

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":51 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  Py_DECREF(__pyx_v_l);
  __pyx_v_l = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":53 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_n; ++__pyx_v_i) {

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":55 */
    __pyx_2 = PyString_FromString((__pyx_v_methods[__pyx_v_i])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    Py_DECREF(__pyx_v_s);
    __pyx_v_s = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":56 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_l, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_INCREF(__pyx_v_s);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_s);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":57 */
    free((__pyx_v_classes[__pyx_v_i]));

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":58 */
    free((__pyx_v_names[__pyx_v_i]));

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":59 */
    free((__pyx_v_methods[__pyx_v_i]));

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":60 */
    free((__pyx_v_infos[__pyx_v_i]));
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":62 */
  __pyx_5 = (__pyx_v_n > 0);
  if (__pyx_5) {

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":63 */
    free(__pyx_v_classes);

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":64 */
    free(__pyx_v_names);

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":65 */
    free(__pyx_v_methods);

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":66 */
    free(__pyx_v_infos);
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":69 */
  Py_INCREF(__pyx_v_l);
  __pyx_r = __pyx_v_l;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("xpa.nslookup");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_l);
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_template);
  return __pyx_r;
}

static PyObject *__pyx_k18p;

static char (__pyx_k18[]) = "XPA$ERROR   XPAGet returned 0!";

static PyObject *__pyx_f_3xpa__get(XPARec (*__pyx_v_xpa),char (*__pyx_v_template),char (*__pyx_v_param)) {
  int __pyx_v_i;
  int __pyx_v_got;
  int (__pyx_v_lens[1]);
  char (*(__pyx_v_bufs[1]));
  char (*(__pyx_v_names[1]));
  char (*(__pyx_v_messages[1]));
  PyObject *__pyx_v_buf;
  PyObject *__pyx_v_mesg;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  __pyx_v_buf = Py_None; Py_INCREF(__pyx_v_buf);
  __pyx_v_mesg = Py_None; Py_INCREF(__pyx_v_mesg);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":84 */
  __pyx_v_got = XPAGet(0,__pyx_v_template,__pyx_v_param,0,__pyx_v_bufs,__pyx_v_lens,__pyx_v_names,__pyx_v_messages,1);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":86 */
  __pyx_1 = (__pyx_v_got == 1);
  if (__pyx_1) {
    __pyx_1 = ((__pyx_v_messages[0]) == 0);
  }
  if (__pyx_1) {

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":87 */
    __pyx_2 = PyString_FromStringAndSize((__pyx_v_bufs[0]),(__pyx_v_lens[0])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    Py_DECREF(__pyx_v_buf);
    __pyx_v_buf = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":89 */
    free((__pyx_v_bufs[0]));

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":90 */
    free((__pyx_v_names[0]));
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":92 */
    __pyx_1 = ((__pyx_v_messages[0]) != 0);
    if (__pyx_1) {

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":93 */
      __pyx_2 = PyString_FromString((__pyx_v_messages[0])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
      Py_DECREF(__pyx_v_mesg);
      __pyx_v_mesg = __pyx_2;
      __pyx_2 = 0;

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":94 */
      free((__pyx_v_messages[0]));
      goto __pyx_L3;
    }
    /*else*/ {

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":96 */
      Py_INCREF(__pyx_k18p);
      Py_DECREF(__pyx_v_mesg);
      __pyx_v_mesg = __pyx_k18p;
    }
    __pyx_L3:;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":98 */
    __pyx_1 = ((__pyx_v_names[0]) != 0);
    if (__pyx_1) {

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":99 */
      free((__pyx_v_names[0]));
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":100 */
    __pyx_1 = ((__pyx_v_bufs[0]) != 0);
    if (__pyx_1) {

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":101 */
      free((__pyx_v_bufs[0]));
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":103 */
    __Pyx_Raise(__pyx_v_mesg, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  }
  __pyx_L2:;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":105 */
  Py_INCREF(__pyx_v_buf);
  __pyx_r = __pyx_v_buf;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("xpa._get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_buf);
  Py_DECREF(__pyx_v_mesg);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_get(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_get(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_template = 0;
  PyObject *__pyx_v_param = 0;
  PyObject *__pyx_r;
  char (*__pyx_1);
  char (*__pyx_2);
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"template","param",0};
  __pyx_v_template = __pyx_k4;
  __pyx_v_param = __pyx_k6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OO", __pyx_argnames, &__pyx_v_template, &__pyx_v_param)) return 0;
  Py_INCREF(__pyx_v_template);
  Py_INCREF(__pyx_v_param);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":108 */
  __pyx_1 = PyString_AsString(__pyx_v_template); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_param); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  __pyx_3 = __pyx_f_3xpa__get(0,__pyx_1,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("xpa.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_template);
  Py_DECREF(__pyx_v_param);
  return __pyx_r;
}

static PyObject *__pyx_k19p;
static PyObject *__pyx_k20p;

static char (__pyx_k19[]) = "";
static char (__pyx_k20[]) = "XPA$ERROR   XPAGet returned 0!";

static PyObject *__pyx_f_3xpa__set(XPARec (*__pyx_v_xpa),char (*__pyx_v_template),char (*__pyx_v_param),PyObject *__pyx_v_buf) {
  int __pyx_v_got;
  int __pyx_v_length;
  char (*(__pyx_v_names[1]));
  char (*(__pyx_v_messages[1]));
  PyObject *__pyx_v_mesg;
  PyObject *__pyx_r;
  int __pyx_1;
  char (*__pyx_2);
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_buf);
  __pyx_v_mesg = Py_None; Py_INCREF(__pyx_v_mesg);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":118 */
  __pyx_1 = PyObject_IsTrue(__pyx_v_buf); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  if (__pyx_1) {

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":119 */
    __pyx_v_length = PyString_Size(__pyx_v_buf);
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":121 */
    Py_INCREF(__pyx_k19p);
    Py_DECREF(__pyx_v_buf);
    __pyx_v_buf = __pyx_k19p;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":122 */
    __pyx_v_length = 0;
  }
  __pyx_L2:;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":124 */
  __pyx_2 = PyString_AsString(__pyx_v_buf); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  __pyx_v_got = XPASet(__pyx_v_xpa,__pyx_v_template,__pyx_v_param,0,__pyx_2,__pyx_v_length,__pyx_v_names,__pyx_v_messages,1);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":126 */
  __pyx_1 = (__pyx_v_got == 1);
  if (__pyx_1) {
    __pyx_1 = ((__pyx_v_messages[0]) == 0);
  }
  if (__pyx_1) {

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":130 */
    free((__pyx_v_names[0]));
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":132 */
    __pyx_1 = ((__pyx_v_messages[0]) != 0);
    if (__pyx_1) {

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":133 */
      __pyx_3 = PyString_FromString((__pyx_v_messages[0])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
      Py_DECREF(__pyx_v_mesg);
      __pyx_v_mesg = __pyx_3;
      __pyx_3 = 0;

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":134 */
      free((__pyx_v_messages[0]));
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":136 */
      Py_INCREF(__pyx_k20p);
      Py_DECREF(__pyx_v_mesg);
      __pyx_v_mesg = __pyx_k20p;
    }
    __pyx_L4:;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":138 */
    __pyx_1 = ((__pyx_v_names[0]) != 0);
    if (__pyx_1) {

      /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":139 */
      free((__pyx_v_names[0]));
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":141 */
    __Pyx_Raise(__pyx_v_mesg, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("xpa._set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_mesg);
  Py_DECREF(__pyx_v_buf);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_set(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_set(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_template = 0;
  PyObject *__pyx_v_param = 0;
  PyObject *__pyx_v_buf = 0;
  PyObject *__pyx_r;
  char (*__pyx_1);
  char (*__pyx_2);
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"template","param","buf",0};
  __pyx_v_template = __pyx_k8;
  __pyx_v_param = __pyx_k10;
  __pyx_v_buf = __pyx_k11;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOO", __pyx_argnames, &__pyx_v_template, &__pyx_v_param, &__pyx_v_buf)) return 0;
  Py_INCREF(__pyx_v_template);
  Py_INCREF(__pyx_v_param);
  Py_INCREF(__pyx_v_buf);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":144 */
  __pyx_1 = PyString_AsString(__pyx_v_template); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_param); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  __pyx_3 = __pyx_f_3xpa__set(0,__pyx_1,__pyx_2,__pyx_v_buf); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("xpa.set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_template);
  Py_DECREF(__pyx_v_param);
  Py_DECREF(__pyx_v_buf);
  return __pyx_r;
}

static char (__pyx_k21[]) = "";

static int __pyx_f_3xpa_3xpa___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_3xpa_3xpa___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_template = 0;
  int __pyx_r;
  char (*__pyx_1);
  static char *__pyx_argnames[] = {"template",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_template)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_template);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":151 */
  __pyx_1 = PyString_AsString(__pyx_v_template); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  ((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_template = __pyx_1;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":152 */
  ((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_xpa = XPAOpen(__pyx_k21);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("xpa.xpa.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_template);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_3xpa___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_3xpa___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":155 */
  XPAClose(((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_xpa);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("xpa.xpa.__del__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_3xpa_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_3xpa_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_param = 0;
  PyObject *__pyx_r;
  char (*__pyx_1);
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"param",0};
  __pyx_v_param = __pyx_k13;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_param)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_param);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":158 */
  __pyx_1 = PyString_AsString(__pyx_v_param); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  __pyx_2 = __pyx_f_3xpa__get(((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_xpa,((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_template,__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("xpa.xpa.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_param);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_3xpa_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_3xpa_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_param = 0;
  PyObject *__pyx_v_buf = 0;
  PyObject *__pyx_r;
  char (*__pyx_1);
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"param","buf",0};
  __pyx_v_param = __pyx_k15;
  __pyx_v_buf = __pyx_k16;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OO", __pyx_argnames, &__pyx_v_param, &__pyx_v_buf)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_param);
  Py_INCREF(__pyx_v_buf);

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":162 */
  __pyx_1 = PyString_AsString(__pyx_v_param); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  __pyx_2 = __pyx_f_3xpa__set(((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_xpa,((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_template,__pyx_1,__pyx_v_buf); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("xpa.xpa.set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_param);
  Py_DECREF(__pyx_v_buf);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_append, "append"},
  {&__pyx_n_get, "get"},
  {&__pyx_n_nslookup, "nslookup"},
  {&__pyx_n_set, "set"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k12p, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k14p, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k18p, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_k19p, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_k20p, __pyx_k20, sizeof(__pyx_k20)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_3xpa_xpa(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_3xpa_xpa *p = (struct __pyx_obj_3xpa_xpa *)o;
  return o;
}

static void __pyx_tp_dealloc_3xpa_xpa(PyObject *o) {
  struct __pyx_obj_3xpa_xpa *p = (struct __pyx_obj_3xpa_xpa *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_3xpa_xpa(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_3xpa_xpa *p = (struct __pyx_obj_3xpa_xpa *)o;
  return 0;
}

static int __pyx_tp_clear_3xpa_xpa(PyObject *o) {
  struct __pyx_obj_3xpa_xpa *p = (struct __pyx_obj_3xpa_xpa *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_3xpa_xpa[] = {
  {"__del__", (PyCFunction)__pyx_f_3xpa_3xpa___del__, METH_VARARGS|METH_KEYWORDS, 0},
  {"get", (PyCFunction)__pyx_f_3xpa_3xpa_get, METH_VARARGS|METH_KEYWORDS, 0},
  {"set", (PyCFunction)__pyx_f_3xpa_3xpa_set, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_xpa = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_xpa = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_xpa = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_xpa = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_3xpa_xpa = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "xpa.xpa", /*tp_name*/
  sizeof(struct __pyx_obj_3xpa_xpa), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_3xpa_xpa, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_xpa, /*tp_as_number*/
  &__pyx_tp_as_sequence_xpa, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_xpa, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_xpa, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_3xpa_xpa, /*tp_traverse*/
  __pyx_tp_clear_3xpa_xpa, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_3xpa_xpa, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_3xpa_3xpa___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_3xpa_xpa, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"nslookup", (PyCFunction)__pyx_f_3xpa_nslookup, METH_VARARGS|METH_KEYWORDS, 0},
  {"get", (PyCFunction)__pyx_f_3xpa_get, METH_VARARGS|METH_KEYWORDS, 0},
  {"set", (PyCFunction)__pyx_f_3xpa_set, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

DL_EXPORT(void) initxpa(void); /*proto*/
DL_EXPORT(void) initxpa(void) {
  __pyx_m = Py_InitModule4("xpa", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_3xpa_xpa) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "xpa", (PyObject *)&__pyx_type_3xpa_xpa) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_ptype_3xpa_xpa = &__pyx_type_3xpa_xpa;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":40 */
  Py_INCREF(__pyx_k1p);
  __pyx_k2 = __pyx_k1p;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":107 */
  Py_INCREF(__pyx_k3p);
  __pyx_k4 = __pyx_k3p;
  Py_INCREF(__pyx_k5p);
  __pyx_k6 = __pyx_k5p;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":143 */
  Py_INCREF(__pyx_k7p);
  __pyx_k8 = __pyx_k7p;
  Py_INCREF(__pyx_k9p);
  __pyx_k10 = __pyx_k9p;
  Py_INCREF(Py_None);
  __pyx_k11 = Py_None;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":157 */
  Py_INCREF(__pyx_k12p);
  __pyx_k13 = __pyx_k12p;

  /* "/Users/jjlee/local/svn/python-sao/xpa.pyx":161 */
  Py_INCREF(__pyx_k14p);
  __pyx_k15 = __pyx_k14p;
  Py_INCREF(Py_None);
  __pyx_k16 = Py_None;
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("xpa");
}

static char *__pyx_filenames[] = {
  "xpa.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
