/* Generated by Pyrex 0.9.8.4 on Tue Apr  7 12:57:13 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#ifndef WIN32
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "stdio.h"
#include "stdlib.h"
#include "xpa.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from xpa */


/* Declarations from implementation of xpa */

struct __pyx_obj_3xpa_xpa {
  PyObject_HEAD
  XPARec *_xpa;
  char *_template;
};


static PyTypeObject *__pyx_ptype_3xpa_xpa = 0;
static PyObject *__pyx_f_3xpa__get(XPARec *,char *,char *); /*proto*/
static PyObject *__pyx_f_3xpa__set(XPARec *,char *,char *,PyObject *); /*proto*/

static char __pyx_k1[] = "g";
static char __pyx_k2[] = "append";
static char __pyx_k3[] = "XPA$ERROR   XPAGet returned 0!";
static char __pyx_k4[] = "XpaException";
static char __pyx_k5[] = "";
static char __pyx_k6[] = "Unknown error : XPAGet returned 0!";
static char __pyx_k7[] = "*";

static PyObject *__pyx_n_XpaException;
static PyObject *__pyx_n_append;

static PyObject *__pyx_k3p;
static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;
static PyObject *__pyx_k7p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_XpaException, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_append, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, 0, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k5p, 0, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, 0, __pyx_k7, sizeof(__pyx_k7)},
  {0, 0, 0, 0}
};

static PyObject *__pyx_d1;
static PyObject *__pyx_d2;
static PyObject *__pyx_d3;
static PyObject *__pyx_d4;
static PyObject *__pyx_d5;
static PyObject *__pyx_d6;
static PyObject *__pyx_d7;
static PyObject *__pyx_d8;
static PyObject *__pyx_d9;


/* Implementation of xpa */

static PyObject *__pyx_f_3xpa_nslookup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_nslookup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_template = 0;
  char **__pyx_v_classes;
  char **__pyx_v_names;
  char **__pyx_v_methods;
  char **__pyx_v_infos;
  int __pyx_v_i;
  int __pyx_v_n;
  PyObject *__pyx_v_l;
  PyObject *__pyx_v_s;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  static char *__pyx_argnames[] = {"template",0};
  __pyx_v_template = __pyx_d1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_template)) return 0;
  Py_INCREF(__pyx_v_template);
  __pyx_v_l = Py_None; Py_INCREF(Py_None);
  __pyx_v_s = Py_None; Py_INCREF(Py_None);

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":48 */
  __pyx_1 = PyString_AsString(__pyx_v_template); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  __pyx_v_n = XPANSLookup(NULL,__pyx_1,__pyx_k1,(&__pyx_v_classes),(&__pyx_v_names),(&__pyx_v_methods),(&__pyx_v_infos));

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":50 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_v_l);
  __pyx_v_l = __pyx_2;
  __pyx_2 = 0;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":52 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_n; ++__pyx_v_i) {

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":54 */
    __pyx_2 = PyString_FromString((__pyx_v_methods[__pyx_v_i])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_v_s);
    __pyx_v_s = __pyx_2;
    __pyx_2 = 0;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":55 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_l, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    Py_INCREF(__pyx_v_s);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_s);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":56 */
    free((__pyx_v_classes[__pyx_v_i]));

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":57 */
    free((__pyx_v_names[__pyx_v_i]));

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":58 */
    free((__pyx_v_methods[__pyx_v_i]));

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":59 */
    free((__pyx_v_infos[__pyx_v_i]));
  }

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":61 */
  __pyx_5 = (__pyx_v_n > 0);
  if (__pyx_5) {

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":62 */
    free(__pyx_v_classes);

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":63 */
    free(__pyx_v_names);

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":64 */
    free(__pyx_v_methods);

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":65 */
    free(__pyx_v_infos);
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":68 */
  Py_INCREF(__pyx_v_l);
  __pyx_r = __pyx_v_l;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("xpa.nslookup");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_l);
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_template);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa__get(XPARec *__pyx_v_xpa,char *__pyx_v_template,char *__pyx_v_param) {
  int __pyx_v_got;
  int __pyx_v_lens[1];
  char *__pyx_v_bufs[1];
  char *__pyx_v_names[1];
  char *__pyx_v_messages[1];
  PyObject *__pyx_v_buf;
  PyObject *__pyx_v_mesg;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_v_buf = Py_None; Py_INCREF(Py_None);
  __pyx_v_mesg = Py_None; Py_INCREF(Py_None);

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":86 */
  __pyx_v_got = XPAGet(NULL,__pyx_v_template,__pyx_v_param,NULL,__pyx_v_bufs,__pyx_v_lens,__pyx_v_names,__pyx_v_messages,1);

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":88 */
  __pyx_1 = (__pyx_v_got == 1);
  if (__pyx_1) {
    __pyx_1 = ((__pyx_v_messages[0]) == NULL);
  }
  if (__pyx_1) {

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":89 */
    __pyx_2 = PyString_FromStringAndSize((__pyx_v_bufs[0]),(__pyx_v_lens[0])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    Py_DECREF(__pyx_v_buf);
    __pyx_v_buf = __pyx_2;
    __pyx_2 = 0;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":91 */
    free((__pyx_v_bufs[0]));

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":92 */
    free((__pyx_v_names[0]));
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":94 */
    __pyx_1 = ((__pyx_v_messages[0]) != NULL);
    if (__pyx_1) {

      /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":95 */
      __pyx_2 = PyString_FromString((__pyx_v_messages[0])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      Py_DECREF(__pyx_v_mesg);
      __pyx_v_mesg = __pyx_2;
      __pyx_2 = 0;

      /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":96 */
      free((__pyx_v_messages[0]));
      goto __pyx_L3;
    }
    /*else*/ {
      Py_INCREF(__pyx_k3p);
      Py_DECREF(__pyx_v_mesg);
      __pyx_v_mesg = __pyx_k3p;
    }
    __pyx_L3:;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":100 */
    __pyx_1 = ((__pyx_v_names[0]) != 0);
    if (__pyx_1) {
      free((__pyx_v_names[0]));
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":102 */
    __pyx_1 = ((__pyx_v_bufs[0]) != 0);
    if (__pyx_1) {
      free((__pyx_v_bufs[0]));
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":105 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_XpaException); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    Py_INCREF(__pyx_v_mesg);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_mesg);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  }
  __pyx_L2:;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":107 */
  Py_INCREF(__pyx_v_buf);
  __pyx_r = __pyx_v_buf;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("xpa._get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_buf);
  Py_DECREF(__pyx_v_mesg);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_get(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_get(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_template = 0;
  PyObject *__pyx_v_param = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"template","param",0};
  __pyx_v_template = __pyx_d2;
  __pyx_v_param = __pyx_d3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OO", __pyx_argnames, &__pyx_v_template, &__pyx_v_param)) return 0;
  Py_INCREF(__pyx_v_template);
  Py_INCREF(__pyx_v_param);
  __pyx_1 = PyString_AsString(__pyx_v_template); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_param); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_3 = __pyx_f_3xpa__get(NULL,__pyx_1,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("xpa.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_template);
  Py_DECREF(__pyx_v_param);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa__set(XPARec *__pyx_v_xpa,char *__pyx_v_template,char *__pyx_v_param,PyObject *__pyx_v_buf) {
  int __pyx_v_got;
  int __pyx_v_length;
  char *__pyx_v_names[1];
  char *__pyx_v_messages[1];
  PyObject *__pyx_v_mesg;
  PyObject *__pyx_r;
  int __pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF(__pyx_v_buf);
  __pyx_v_mesg = Py_None; Py_INCREF(Py_None);

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":120 */
  __pyx_1 = PyObject_IsTrue(__pyx_v_buf); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
  if (__pyx_1) {
    __pyx_v_length = PyString_Size(__pyx_v_buf);
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":123 */
    Py_INCREF(__pyx_k5p);
    Py_DECREF(__pyx_v_buf);
    __pyx_v_buf = __pyx_k5p;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":124 */
    __pyx_v_length = 0;
  }
  __pyx_L2:;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":126 */
  __pyx_2 = PyString_AsString(__pyx_v_buf); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  __pyx_v_got = XPASet(__pyx_v_xpa,__pyx_v_template,__pyx_v_param,NULL,__pyx_2,__pyx_v_length,__pyx_v_names,__pyx_v_messages,1);

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":128 */
  __pyx_1 = (__pyx_v_got == 1);
  if (__pyx_1) {
    __pyx_1 = ((__pyx_v_messages[0]) == NULL);
  }
  if (__pyx_1) {

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":132 */
    free((__pyx_v_names[0]));
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":134 */
    __pyx_1 = ((__pyx_v_messages[0]) != NULL);
    if (__pyx_1) {

      /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":135 */
      __pyx_3 = PyString_FromString((__pyx_v_messages[0])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
      Py_DECREF(__pyx_v_mesg);
      __pyx_v_mesg = __pyx_3;
      __pyx_3 = 0;

      /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":136 */
      free((__pyx_v_messages[0]));
      goto __pyx_L4;
    }
    /*else*/ {
      Py_INCREF(__pyx_k6p);
      Py_DECREF(__pyx_v_mesg);
      __pyx_v_mesg = __pyx_k6p;
    }
    __pyx_L4:;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":140 */
    __pyx_1 = ((__pyx_v_names[0]) != 0);
    if (__pyx_1) {
      free((__pyx_v_names[0]));
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":143 */
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_XpaException); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    Py_INCREF(__pyx_v_mesg);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_mesg);
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("xpa._set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_mesg);
  Py_DECREF(__pyx_v_buf);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_set(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_set(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_template = 0;
  PyObject *__pyx_v_param = 0;
  PyObject *__pyx_v_buf = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"template","param","buf",0};
  __pyx_v_template = __pyx_d4;
  __pyx_v_param = __pyx_d5;
  __pyx_v_buf = __pyx_d6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOO", __pyx_argnames, &__pyx_v_template, &__pyx_v_param, &__pyx_v_buf)) return 0;
  Py_INCREF(__pyx_v_template);
  Py_INCREF(__pyx_v_param);
  Py_INCREF(__pyx_v_buf);
  __pyx_1 = PyString_AsString(__pyx_v_template); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_param); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_3 = __pyx_f_3xpa__set(NULL,__pyx_1,__pyx_2,__pyx_v_buf); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("xpa.set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_template);
  Py_DECREF(__pyx_v_param);
  Py_DECREF(__pyx_v_buf);
  return __pyx_r;
}

static int __pyx_f_3xpa_3xpa___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_3xpa_3xpa___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_template = 0;
  int __pyx_r;
  char *__pyx_1;
  static char *__pyx_argnames[] = {"template",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_template)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_template);

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":154 */
  __pyx_1 = PyString_AsString(__pyx_v_template); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  ((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_template = __pyx_1;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":155 */
  ((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_xpa = XPAOpen(__pyx_k5);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("xpa.xpa.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_template);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_3xpa___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_3xpa___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  XPAClose(((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_xpa);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_3xpa_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_3xpa_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_param = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"param",0};
  __pyx_v_param = __pyx_d7;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_param)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_param);
  __pyx_1 = PyString_AsString(__pyx_v_param); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  __pyx_2 = __pyx_f_3xpa__get(((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_xpa,((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_template,__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("xpa.xpa.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_param);
  return __pyx_r;
}

static PyObject *__pyx_f_3xpa_3xpa_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3xpa_3xpa_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_param = 0;
  PyObject *__pyx_v_buf = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"param","buf",0};
  __pyx_v_param = __pyx_d8;
  __pyx_v_buf = __pyx_d9;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OO", __pyx_argnames, &__pyx_v_param, &__pyx_v_buf)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_param);
  Py_INCREF(__pyx_v_buf);
  __pyx_1 = PyString_AsString(__pyx_v_param); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 165; goto __pyx_L1;}
  __pyx_2 = __pyx_f_3xpa__set(((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_xpa,((struct __pyx_obj_3xpa_xpa *)__pyx_v_self)->_template,__pyx_1,__pyx_v_buf); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 165; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("xpa.xpa.set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_param);
  Py_DECREF(__pyx_v_buf);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_3xpa_xpa(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_3xpa_xpa(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_3xpa_xpa[] = {
  {"__del__", (PyCFunction)__pyx_f_3xpa_3xpa___del__, METH_VARARGS|METH_KEYWORDS, 0},
  {"get", (PyCFunction)__pyx_f_3xpa_3xpa_get, METH_VARARGS|METH_KEYWORDS, 0},
  {"set", (PyCFunction)__pyx_f_3xpa_3xpa_set, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_xpa = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_xpa = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_xpa = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_xpa = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_3xpa_xpa = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "xpa.xpa", /*tp_name*/
  sizeof(struct __pyx_obj_3xpa_xpa), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_3xpa_xpa, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_xpa, /*tp_as_number*/
  &__pyx_tp_as_sequence_xpa, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_xpa, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_xpa, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_3xpa_xpa, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_3xpa_3xpa___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_3xpa_xpa, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"nslookup", (PyCFunction)__pyx_f_3xpa_nslookup, METH_VARARGS|METH_KEYWORDS, 0},
  {"get", (PyCFunction)__pyx_f_3xpa_get, METH_VARARGS|METH_KEYWORDS, 0},
  {"set", (PyCFunction)__pyx_f_3xpa_set, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initxpa(void); /*proto*/
PyMODINIT_FUNC initxpa(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("xpa", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_3xpa_xpa) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "xpa", (PyObject *)&__pyx_type_3xpa_xpa) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  __pyx_ptype_3xpa_xpa = &__pyx_type_3xpa_xpa;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":39 */
  Py_INCREF(__pyx_k7p);
  __pyx_d1 = __pyx_k7p;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":71 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  Py_INCREF(PyExc_Exception);
  PyTuple_SET_ITEM(__pyx_2, 0, PyExc_Exception);
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_XpaException, "xpa"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_XpaException, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":109 */
  Py_INCREF(__pyx_k7p);
  __pyx_d2 = __pyx_k7p;
  Py_INCREF(__pyx_k5p);
  __pyx_d3 = __pyx_k5p;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":146 */
  Py_INCREF(__pyx_k7p);
  __pyx_d4 = __pyx_k7p;
  Py_INCREF(__pyx_k5p);
  __pyx_d5 = __pyx_k5p;
  Py_INCREF(Py_None);
  __pyx_d6 = Py_None;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":160 */
  Py_INCREF(__pyx_k5p);
  __pyx_d7 = __pyx_k5p;

  /* "/bulk/blackstone1/lee/local/svn/python-sao/xpa.pyx":164 */
  Py_INCREF(__pyx_k5p);
  __pyx_d8 = __pyx_k5p;
  Py_INCREF(Py_None);
  __pyx_d9 = Py_None;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("xpa");
}

static char *__pyx_filenames[] = {
  "xpa.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
